### ISSUE TITLE
Add option for printing task duration summary

### ISSUE THREAD

**Issue by saatchiCEO** [gruntjs/grunt#872] opened 2013-08-19 15:38 UTC
![A weird illustration](https://f.cloud.github.com/assets/1426925/987106/4669dda4-08e5-11e3-98e9-e4e4f5786bf2.jpg)

**Comment by shama** [comment] 2016-01-31 02:55
Closing as a duplicate of https://github.com/gruntjs/grunt/issues/830

**Closed by shama** 2016-01-31 02:55 UTC
Labels: feature, prolog
