### ISSUE TITLE
grunt.file.delete incorrectly reports path as outside current directory

### ISSUE THREAD

**Issue by rockerest** [gruntjs/grunt#1469] opened 2016-02-23 19:36 UTC
```
grunt-cli v0.1.13
grunt v0.4.5
node v5.7.0
npm 3.6.0
```

Given the following task:

```
grunt.registerTask( "clean", "Wipe ./build", function(){
    if( grunt.file.isDir( "./build" ) ){
        grunt.file.delete( "./build" );
    }
} );
```

And the directory structure:
```
/
|---Gruntfile.js
|---build/
    |--- [files]
```

Running `grunt clean` fails and reports a warning:
```
Warning: Cannot delete files outside the current working directory. Use --force to continue.
```

Is this expected behavior?

On my \*nix terminal any combination of `./`, `/./`, etc. always results in the current path.
From my perspective, requesting that `./build` be deleted is *explicitly* asking that the folder named `build` in the `cwd` be deleted, making this warning (and task failure) objectively incorrect.

I could be missing a nuance about how this is resolved, but having an error about not being able to delete files outside the cwd while explicitly requesting to start at the cwd feels off to me.

I'm also too unfamiliar with node to know if this is an issue with Grunt (maybe [here](https://github.com/gruntjs/grunt/blob/master/lib/grunt/file.js#L463) or [here](https://github.com/gruntjs/grunt/blob/master/lib/grunt/file.js#L439)?) or with Node's fs or path modules themselves.

**Comment by vladikoff** [comment] 2016-02-23 19:40
@rockerest what version of node?

**Comment by vladikoff** [comment] 2016-02-23 19:40
@rockerest see https://github.com/gruntjs/grunt-contrib-clean/issues/85  and https://github.com/nodejs/node/issues/5383

**Comment by rockerest** [comment] 2016-02-23 23:23
node version `3.6.0` and npm version `3.6.0`.

I'll also update the main issue to keep it all in one place.

Re: the issue you linked - I *strongly* believe the issue resides out there in node.
I don't know whether to leave this issue open or not: I think it's directly related, but dealing with `.` might be slightly different than whatever `path.relative` is doing.

I suppose it's up to you as a member of the Grunt team if you want to close here or not.

**Comment by sibsibsib** [comment] 2016-02-24 20:12
I just ran into this too. The issue is that .relative() is returning '../../whatever' instead of just '../' which causes the regex test in grunt's code (https://github.com/gruntjs/grunt/blob/master/lib/grunt/file.js#L444) to return false.

**Comment by vladikoff** [comment] 2016-02-24 20:15
https://github.com/nodejs/node/issues/5383

**Comment by vladikoff** [comment] 2016-02-24 20:15
https://github.com/nodejs/node/issues/5400

**Comment by aranaea** [comment] 2016-02-29 04:33
I ran into this and dug into it enough to find the problem.  Grunt's unit tests were failing when run with node 5.7 so that made it easier to chase down.  I also verified that the unit tests still pass with this change and node 5.6.

**Comment by shama** [comment] 2016-02-29 04:34
Closing this issue as this is a regression with Node.js and has been fixed for the `5.7.1` release. We don't need to add a workaround to Grunt for this.

**Closed by shama** 2016-02-29 04:34 UTC

**Comment by aranaea** [comment] 2016-02-29 04:40
@shama, the arguments being passed to path.relative are in the wrong order.  Even if the issue is resolved in Node 5.7.1 the grunt code is wrong and uses a regex to catch itself.

**Comment by shama** [comment] 2016-02-29 05:01
@aranaea Sorry, I'm not understanding the problem. If the regression is fixed in Node.js, what issue is that patch fixing?

**Comment by aranaea** [comment] 2016-02-29 05:27
Hi @shama

The way the code is currently written it asks for the relative path from the target directory to the current and expects only `../` characters in the result.  It seems more correct, and intuitive, to get the relative path from the current directory to the target and check to see if it begins with `..`.   This has the added benefit of working in node 5.7 and 5.6.

Thanks for thinking about this.
