### ISSUE TITLE
error Cannot read property 'find' of undefined

### ISSUE THREAD

**Issue by inorganik** [gruntjs/grunt#1592] opened 2017-06-05 16:44 UTC
Hi there, I recently updated npm and node, and when I run `npm install grunt -g` I ran into the following error:

`error Cannot read property 'find' of undefined`

Here's what was at the end of the log:

```
1310 silly extract load-json-file@1.1.0
1311 silly pacote trying load-json-file@https://registry.npmjs.org/load-json-file/-/load-json-file-1.1.0.tgz by hash: sha1-lWkFcI1YtLq0wiYbBPWfMcmTdMA=
1312 verbose stack TypeError: Cannot read property 'find' of undefined
1312 verbose stack     at opts.integrity.digests.find.hash (/usr/local/lib/node_modules/npm/node_modules/ssri/index.js:264:33)
1312 verbose stack     at Array.find (native)
1312 verbose stack     at Transform.on (/usr/local/lib/node_modules/npm/node_modules/ssri/index.js:263:15)
1312 verbose stack     at emitNone (events.js:110:20)
1312 verbose stack     at Transform.emit (events.js:207:7)
1312 verbose stack     at endReadableNT (_stream_readable.js:1045:12)
1312 verbose stack     at _combinedTickCallback (internal/process/next_tick.js:102:11)
1312 verbose stack     at process._tickCallback (internal/process/next_tick.js:161:9)
1313 verbose cwd /Users/Jamie/Sites/
1314 verbose Darwin 16.5.0
1315 verbose argv "/usr/local/Cellar/node/8.0.0_1/bin/node" "/usr/local/bin/npm" "install" "grunt" "-g"
1316 verbose node v8.0.0
1317 verbose npm  v5.0.2
1318 error Cannot read property 'find' of undefined
1319 verbose exit [ 1, true ]
```

**Comment by shama** [comment] 2017-06-05 16:48
Closing as a duplicate of https://github.com/gruntjs/grunt-cli/issues/114

Looks like running `npm cache verify` will fix the problem: https://github.com/zkat/ssri/issues/4#issuecomment-306039002

**Closed by shama** 2017-06-05 16:48 UTC

**Comment by Yugloocamai** [comment] 2017-06-13 22:29
npm cache verify worked for me! 👍

**Comment by atlabiz** [comment] 2017-06-29 09:37
and for me

**Comment by nabaragpaul** [comment] 2017-07-28 08:00
and for me too ...thanks

**Comment by smarcov** [comment] 2017-08-03 15:38
&4me  =)

**Comment by WadeZhu** [comment] 2017-11-22 10:43
&4me2 thx =)

**Comment by mbarker1221** [comment] 2018-03-27 06:39
it did not work for me
