### ISSUE TITLE
[Bug] Output color = background color if I build site via Grunt

### ISSUE THREAD

**Issue by Kristinita** [gruntjs/grunt#1589] opened 2017-05-07 09:59 UTC
Please, see detailed issue description [**in my Super User question**](https://superuser.com/q/1198421/572069).

Thanks.

**Comment by shama** [comment] 2017-05-08 03:02
Here is a probably related issue: https://github.com/Maximus5/ConEmu/issues/195

Closing as not a bug as Grunt doesn't pick the colors, it uses [chalk](https://www.npmjs.com/package/chalk) to set color indexes in which the terminal themes map to actual colors. So if the foreground is the same/similar to the background, it's going to be a problem with the shell and/or theme.

**Closed by shama** 2017-05-08 03:02 UTC

**Comment by Kristinita** [comment] 2017-05-08 06:22
@shama , @Maximus5 — ConEmu author — [**say me**](https://superuser.com/posts/comments/1742448):

> Grunt sets your `foreground = background`. That's the problem.

Where I need to write issue, that the problem will solved?

Thanks.

**Comment by Maximus5** [comment] 2017-05-08 08:28
Console application shall return colors to the state it was started. Other behavior breaks users experience.

**Comment by shama** [comment] 2017-05-08 15:48
> Grunt sets your foreground = background. That's the problem.

If this were true, I suspect we'd get a lot more issues about colors.

I don't use nor am familiar with ConEmu but if you or somebody else would like to look into the issue and find that it is in fact a problem with Grunt, I'd be happy to review a patch for it. Thanks!

**Comment by dmethvin** [comment] 2017-05-09 01:21
I tried to help but the referenced question doesn't seem to have a reference to the gruntfile. If grunt is setting the foreground and background to the same color, the most likely reason is that some code in the gruntfile is asking for the foreground and background be set to the same color.

**Comment by Kristinita** [comment] 2017-05-09 03:44
@dmethvin ,

+ [**my project**](https://github.com/Kristinita/KristinitaPelican),
+ [**my `Gruntfile.coffee` file**](https://github.com/Kristinita/KristinitaPelican/blob/master/Gruntfile.coffee).

Thanks.

**Comment by Kristinita** [comment] 2018-02-15 16:04
The problem is relevant in 2018.

Thanks.

**Comment by shama** [comment] 2018-02-15 16:14
@Kristinita I don't use nor am familiar with ConEmu but if you or somebody else would like to look into the issue and find that it is in fact a problem with Grunt, I'd be happy to review a patch for it. Thanks!

**Comment by wggley** [comment] 2018-03-08 22:46
I traced back to see when this problem started ocurring and discovered that it started on Node.js 6.11.0:
https://github.com/nodejs/node/blob/master/doc/changelogs/CHANGELOG_V6.md#6.11.0

Maybe something related to libuv @Maximus5 ?

**Comment by wggley** [comment] 2018-03-08 22:52
Testing previous releases of nodejs, colors are ok:
I'm using nvm to switch between nodejs versions:
![image](https://user-images.githubusercontent.com/13734836/37181032-221816a2-230a-11e8-8b5e-22cda98944a4.png)
![image](https://user-images.githubusercontent.com/13734836/37181039-2b77181a-230a-11e8-9911-4f61ff4bf53d.png)

**Comment by Maximus5** [comment] 2018-03-08 23:11
Perhaps it's related to https://github.com/Maximus5/ConEmu/commit/58bc3a261c07e5c75cae81ed2a8020ab880b750e
