### ISSUE TITLE
Grunt option, issue with --option. leading zeros are truncated

### ISSUE THREAD

**Issue by futur** [gruntjs/grunt#1474] opened 2016-02-28 13:59 UTC
I'm running on _Mac 10.10.5_ with the following grunt installed,
```
grunt-cli v0.1.13
grunt v0.4.5
```

I have a task that will take a 3 digit number and it can be 000 or 099 or 002 or 999. Grunt option is converting the number starting with 0 to just number. 

> Example, 099 is returned as 99 by the grunt.option() function. One more example is 002 is returned as 2. 

**Code Sample**

```
module.exports = function(grunt) {

  // Project configuration.
  grunt.initConfig({
    pkg: grunt.file.readJSON('package.json'),
    prompt: {
    feature: {
      options: {
        questions: [
          {
            config: 'addFeature',
            type: 'input', 
            message: 'Enter the name of the feature. Input text and press enter.',
            default: 'testFeature', 
          }
        ],
        then:function(results,done){
          var target = grunt.option('target'); // leading zeros are getting removed right here
          // var target = grunt.option('target').toString(); // Doesnt work.
          // var target = grunt.option('target')+ ""; // Doesnt work too.
          grunt.log.ok("User input is : "+ results.addFeature); // This captures leading zero values OK values OK.
          grunt.log.ok("User target flag input is : "+ target); // This prints without leading zero.
        }
      }
    }
    }
  });

  // Load the plugin that provides the "uglify" task.
  grunt.loadNpmTasks('grunt-prompt');

  // Default task(s).
  grunt.registerTask('default', ['prompt:feature']);

};
```

**Comment by shama** [comment] 2016-02-28 16:00
Duplicate of https://github.com/gruntjs/grunt/issues/1421 and fixed in `grunt@1.0.0-rc1`.

**Closed by shama** 2016-02-28 16:00 UTC
