### ISSUE TITLE
claims task X not found when problem is bad package

### ISSUE THREAD

**Issue by z0d14c** [gruntjs/grunt#1347] opened 2015-06-08 15:42 UTC
A project I am working on had a bad package dependency that necessitated rolling back to another package in our package.json file. This is all well and good, but when I tried to run "grunt X" (where X is the name of our main grunt task) I received the following:

> Loading "Gruntfile.js" tasks...ERROR
> >> TypeError: Cannot read property 'prototype' of undefined
> Warning: Task "X" not found. Use --force to continue.

The TypeError, far as I can tell, resulted from something going wrong with the package dependency, yet the message complains that task X is not found. As soon as the dependency is fixed this message goes away, because obviously the task is defined appropriately. I am not well versed enough in Grunt to fix this myself right now but maybe it is a quick fix that someone else could address.

**Comment by silkentrance** [comment] 2015-08-05 18:40
In which case you should use ```--verbose``` to get more information on the exception being thrown.

Otherwise, you may take a look at https://github.com/gruntjs/grunt/blob/0a968d0becd81e78851da108b0961cc42a4744c5/lib/grunt/task.js#L323

where the original error is caught and then reported.

Grunt will not fail early here and instead will try to run any tasks that are available, therefore the info that the specified task was not found.

**Comment by shama** [comment] 2015-11-24 02:15
I'm not sure what the issue is but I'd be happy to take a look at your Gruntfile to try and help. `Cannot read property 'prototype' of undefined` indicates something is going wrong in your task. Running `grunt --stack` will give you a stack trace to better indicate where the error originates from to fix.

Closing as this doesn't appear to be an issue with Grunt.

**Closed by shama** 2015-11-24 02:15 UTC
