### ISSUE TITLE
Can't install grunt : 404 Not Found: flatmap-stream@0.1.1

### ISSUE THREAD

**Issue by Clm-Roig** [gruntjs/grunt#1655] opened 2018-11-27 08:56 UTC
It looks like the dependency flatmap-stream is infected according to these threads: 
- [https://github.com/dominictarr/event-stream/issues/116](https://github.com/dominictarr/event-stream/issues/116)
- [https://github.com/dominictarr/event-stream/issues/115](https://github.com/dominictarr/event-stream/issues/115)

I'm not able anymore to install grunt because of this, I'm getting a 404 on this package. 
(Sorry if I'm misunderstanding something, it's my first "public" issue on GitHub :sweat_smile: )

**Comment by shama** [comment] 2018-11-27 09:32
Can you provide more detail? Perhaps run `find / -type d -name "flatmap-stream" -print 2>/dev/null` and tell me which paths have `flatmap-stream` in them? Or list your `package.json` so I can investigate which other dependencies might be installing that one instead?

AFIAK, Grunt doesn't have `event-stream` nor `flatmap-stream` as dependencies or child dependencies. I have lots of various Grunt setups installed on my machine but can't find any instance of that dependency installed. If you have found one linked to Grunt please let us know the specific dependency so we can fix it. Thanks!

**Comment by Clm-Roig** [comment] 2018-11-27 12:37
Sorry for the delay, I tried other things. 
It seems that is not especially related to grunt: I removed all the grunt dependencies from my package.json, deleted all the /node_modules folder and the error still appears...

**Comment by shama** [comment] 2018-11-27 16:05
Can you paste the error? I'm not able to reproduce so any additional information you provide will help. The contents of your `package.json` or a stack trace from the error would also help.

**Comment by shama** [comment] 2018-12-03 05:30
Closing as invalid. If you still think this is an issue please comment with the info requested. Thanks!

**Closed by shama** 2018-12-03 05:30 UTC
